In [1]:
import numpy as np

# **Arrays**

In [3]:
orig = [1, 2, 3, 4, 5]
np_array = np.array(orig)
np_array

array([1, 2, 3, 4, 5])

In [7]:
np_array * 2

array([ 2,  4,  6,  8, 10])

In [29]:
orig * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# Ranges

In [9]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(0, 5, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

# More Ranges

In [13]:
np.linspace(1, 10)

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [20]:
np.linspace(1, 15, 5)

array([  1. ,   4.5,   8. ,  11.5,  15. ])

In [21]:
np.arange(1, 15, 5)

array([ 1,  6, 11])

In [24]:
np.linspace(1, 15, 5, endpoint=False)

array([  1. ,   3.8,   6.6,   9.4,  12.2])

In [26]:
np.linspace(1, 15, 5, endpoint=True)

array([  1. ,   4.5,   8. ,  11.5,  15. ])

In [28]:
result, step = np.linspace(1, 15, 5, endpoint=True, retstep=True)
step

3.5

# N-Dimensional Arrays

In [34]:
np.array(10) # scalar (0-dimensional array)

array(10)

In [35]:
np.array(10) * 2

20

In [36]:
np.array([1, 2, 3, 4]) # (1-dimensional)

array([1, 2, 3, 4])

In [39]:
x = np.array([[1, 2, 3], [1, 2, 3]])  # (2-demensional etc)
x

array([[1, 2, 3],
       [1, 2, 3]])

In [40]:
np.ndim(x)

2

In [41]:
x.dtype

dtype('int64')

In [43]:
y = np.array([1.1, 1.2, 1.3])
y.dtype

dtype('float64')

In [45]:
np.shape(x)
# or
x.shape

(2, 3)

In [48]:
x.T  # transpose

array([[1, 1],
       [2, 2],
       [3, 3]])

In [49]:
x.T.shape

(3, 2)

# Numpy arrays can be used similar to python arrays

In [50]:
x = np.array([1, 2, 3, 4, 5])
x[1]

2

In [52]:
x[1:5]

array([2, 3, 4, 5])

In [60]:
y = np.array([[1, 2, 3], [4, 5, 6]])
y[1][1]

5

In [61]:
y[1, 1] # this way is better in numpy (faster)

5

# Reshape

In [70]:
x = np.arange(20)
y = x.reshape(4, 5)

In [71]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
y[2, 2]

12

# View vs Copy

In [88]:
py_array = list(range(20))
np_array = np.arange(20)

In [89]:
x = py_array[1:6]
y = np_array[1:6]

print(x)
print(y)

# so far so good

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [90]:
py_array[5] = 99
np_array[5] = 99

In [91]:
print(x)
print(y)

[1, 2, 3, 4, 5]
[ 1  2  3  4 99]


In [93]:
z = np_array.copy()

# Shorthand functions

In [83]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [84]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [85]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [86]:
x = np.arange(20).reshape(4, 5)
np.ones_like(x)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])